// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste.Models
{
    public partial class BackdoorServiceRequest
    {
        public int BackdoorId { get; set; }
        public string MedicalNeedForBackdoorService { get; set; }
        public string Over75NoOneToTransportCans { get; set; }
        public string WantsToEnrollInFeeBasedService { get; set; }
        public string ChoosingNotToSignUpForBackdoorService { get; set; }
        public string CurrentlyEnrolledInCurbSideRecycling { get; set; }
        public string WantsRecyclingCart { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int? StreetNumber { get; set; }
        public string StreetNamePrefix { get; set; }
        public string StreetName { get; set; }
        public string StreetNameSuffix { get; set; }
        public string StreetSuffixDirection { get; set; }
        public string UnitNumber { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public DateTime? StatusDate { get; set; }
        public DateTime? CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public string Recycler { get; set; }
        public string Comments { get; set; }
        public string AltName { get; set; }
        public string AltPhone { get; set; }
        public decimal? PointX { get; set; }
        public decimal? PointY { get; set; }
        public string SaveDuplicate { get; set; }
    }
}