// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Configurations;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models;
using System.Configuration;
#nullable disable

#nullable disable

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle
{
    public partial class WRM_TrashRecycle : DbContext
    {
        public WRM_TrashRecycle()
        {
        }

        public WRM_TrashRecycle(DbContextOptions<WRM_TrashRecycle> options)
            : base(options)
        {
        }

        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<BackDoorPickup> BackDoorPickup { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Kgisaddress> Kgisaddress { get; set; }
        public virtual DbSet<Resident> Resident { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
            if (!optionsBuilder.IsConfigured)
                {
                var connectionString = ConfigurationManager.ConnectionStrings["WRM_TrashRecycle"].ConnectionString;
                optionsBuilder.UseSqlServer(connectionString,options => options.MinBatchSize(1).MaxBatchSize(1));

                }
            }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.AddressConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BackDoorPickupConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CartConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.KgisaddressConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ResidentConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
