// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Configurations;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models;

#nullable disable

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle
{
    public partial class WRM_TrashRecycle : DbContext
    {
        public WRM_TrashRecycle()
        {
        }

        public WRM_TrashRecycle(DbContextOptions<WRM_TrashRecycle> options)
            : base(options)
        {
        }

        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<BackDoorPickup> BackDoorPickup { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<KgisResidentAddressView> KgisResidentAddressView { get; set; }
        public virtual DbSet<Resident> Resident { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=TEST;Initial Catalog=WRM_TrashRecycle;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.AddressConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BackDoorPickupConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CartConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.KgisResidentAddressViewConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ResidentConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
