// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste.Configurations;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste.Models;

#nullable disable

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste
{
    public partial class SolidWaste : DbContext
    {
        public SolidWaste()
        {
        }

        public SolidWaste(DbContextOptions<SolidWaste> options)
            : base(options)
        {
        }

        public virtual DbSet<BackdoorServiceRequest> BackdoorServiceRequest { get; set; }
        public virtual DbSet<RecyclingRequest> RecyclingRequest { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=TEST;Initial Catalog=solidwaste;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.BackdoorServiceRequestConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RecyclingRequestConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
