// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste.Configurations;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste.Models;
using System.Configuration;

#nullable disable

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste
{
    public partial class SolidWaste : DbContext
    {
        public SolidWaste()
        {
        }

        public SolidWaste(DbContextOptions<SolidWaste> options)
            : base(options)
        {
        }

        public virtual DbSet<BackdoorServiceRequest> BackdoorServiceRequest { get; set; }
        public virtual DbSet<RecyclingRequest> RecyclingRequest { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connectionString = ConfigurationManager.ConnectionStrings["SolidWasteDatabase"].ConnectionString;
                optionsBuilder.UseSqlServer(connectionString);

                }
            }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.BackdoorServiceRequestConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RecyclingRequestConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
