// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste.Configurations;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste.Models;
#nullable disable

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.SolidWaste
{
    public partial class SolidWaste : DbContext
    {
        public SolidWaste()
        {
        }

        public SolidWaste(DbContextOptions<SolidWaste> options)
            : base(options)
        {
        }

        public virtual DbSet<BackdoorServiceRequest> BackdoorServiceRequest { get; set; }
        public virtual DbSet<RecyclingRequest> RecyclingRequest { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.BackdoorServiceRequestConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RecyclingRequestConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
