// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models
{
    public partial class Address
    {
        public Address()
        {
            BackDoorPickup = new HashSet<BackDoorPickup>();
            Cart = new HashSet<Cart>();
            Resident = new HashSet<Resident>();
        }

        public int AddressId { get; set; }
        public string GisparcelId { get; set; }
        public int StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string UnitNumber { get; set; }
        public string ZipCode { get; set; }
        public string NumberUnits { get; set; }
        public string AddressType { get; set; }
        public string GisaddressUseType { get; set; }
        public bool? RecyclingPickup { get; set; }
        public string RecyclingStatus { get; set; }
        public DateTime? RecyclingStatusDate { get; set; }
        public DateTime? RecyclingRequestedDate { get; set; }
        public DateTime? RecyclingApprovalDate { get; set; }
        public DateTime? RecyclingWithdrawalDate { get; set; }
        public string RecycleDayOfWeek { get; set; }
        public string RecycleFrequency { get; set; }
        public string RecyclingComment { get; set; }
        public string TrashDayOfWeek { get; set; }
        public bool? TrashPickup { get; set; }
        public decimal? GispointX { get; set; }
        public decimal? GispointY { get; set; }
        public decimal? Gislatitude { get; set; }
        public decimal? Gislongitude { get; set; }
        public string Comment { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual ICollection<BackDoorPickup> BackDoorPickup { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<Resident> Resident { get; set; }
    }
}