// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models
{
    public partial class BackDoorPickup
    {
        [Key]
        public int BackDoorPickupID { get; set; }
        public int AddressID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string BackdoorType { get; set; }
        [StringLength(25)]
        [Unicode(false)]
        public string BackdoorStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BackdoorStatusDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BackdoorApprovalDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BackdoorWithdrawalDate { get; set; }
        [StringLength(512)]
        [Unicode(false)]
        public string Note { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string CreateUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string UpdateUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [ForeignKey("AddressID")]
        [InverseProperty("BackDoorPickup")]
        public virtual Address Address { get; set; }
    }
}