// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models
{
    public partial class Cart
    {
        public int CartId { get; set; }
        public int? AddressId { get; set; }
        public string CartSerialNumber { get; set; }
        public string CartSize { get; set; }
        public DateTime? SerialNumberReceivedDate { get; set; }
        public string Note { get; set; }
        public bool? IsRecyclingCart { get; set; }
        public string CartStatus { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual Address Address { get; set; }
    }
}