// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models
{
    public partial class CommercialAccount
    {
        [Key]
        public int AddressCommercialID { get; set; }
        public int AddressID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string CommercialAccountNumber { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string CommercialAccountName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommercialAccountCreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommercialAccountEndDate { get; set; }
        [StringLength(25)]
        [Unicode(false)]
        public string CommercialAccountStatus { get; set; }
        public bool? HasDowntownCrewPickup { get; set; }
        public bool? HasCommercialBillingAlert { get; set; }
        public int? CommercialStreetNumber { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string CommercialStreetName { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CommercialUnitNumber { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CommercialPOBoxNumber { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CommercialCity { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CommercialState { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CommercialZipCode { get; set; }
        [StringLength(512)]
        [Unicode(false)]
        public string BillingNote { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string CreateUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string UpdateUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [ForeignKey("AddressID")]
        [InverseProperty("CommercialAccount")]
        public virtual Address Address { get; set; }
    }
}