// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models
{
    public partial class KgisResidentAddressView
    {
        public decimal? AddressStatus { get; set; }
        public decimal? AddressNum { get; set; }
        public string Prefix { get; set; }
        public string StreetBasename { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string Unit { get; set; }
        public string UnitType { get; set; }
        public decimal? ZipCode { get; set; }
        public string StateCode { get; set; }
        public decimal? PointX { get; set; }
        public decimal? PointY { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public string AddressUseType { get; set; }
        public string Parcelid { get; set; }
        public decimal? Jurisdiction { get; set; }
    }
}