// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models
{
    public partial class Resident
    {
        [Key]
        public int ResidentID { get; set; }
        public int AddressID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string LastName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Phone { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column(TypeName = "text")]
        public string Note { get; set; }
        public bool? SendEmailNewsletter { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string CreateUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string UpdateUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [ForeignKey("AddressID")]
        [InverseProperty("Resident")]
        public virtual Address Address { get; set; }
    }
}