//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRM_TrashRecyclePopulation {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class solidwaste : global::System.Configuration.ApplicationSettingsBase {
        
        private static solidwaste defaultInstance = ((solidwaste)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new solidwaste())));
        
        public static solidwaste Default {
            get {
                return defaultInstance;
            }
        }
    }
}
