// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle;


namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Configurations
{
    public partial class BackDoorPickupConfiguration : IEntityTypeConfiguration<BackDoorPickup>
    {
        public void Configure(EntityTypeBuilder<BackDoorPickup> entity)
        {
            entity.Property(e => e.BackDoorPickupId).HasColumnName("BackDoorPickupID");

            entity.Property(e => e.AddressId).HasColumnName("AddressID");

            entity.Property(e => e.BackdoorApprovalDate).HasColumnType("datetime");

            entity.Property(e => e.BackdoorStatus)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.BackdoorStatusDate).HasColumnType("datetime");

            entity.Property(e => e.BackdoorType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.BackdoorWithdrawalDate).HasColumnType("datetime");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");

            entity.Property(e => e.CreateUser)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Note)
                .HasMaxLength(512)
                .IsUnicode(false);

            entity.Property(e => e.ResidentId).HasColumnName("ResidentID");

            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.Property(e => e.UpdateUser)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Address)
                .WithMany(p => p.BackDoorPickup)
                .HasForeignKey(d => d.AddressId)
                .HasConstraintName("FK__BackDoorP__Addre__25077354");

            entity.HasOne(d => d.Resident)
                .WithMany(p => p.BackDoorPickup)
                .HasForeignKey(d => d.ResidentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BackDoorP__Resid__24134F1B");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BackDoorPickup> entity);
    }
}
