// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models;

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Configurations
{
    public partial class CommercialAccountConfiguration : IEntityTypeConfiguration<CommercialAccount>
    {
        public void Configure(EntityTypeBuilder<CommercialAccount> entity)
        {
            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.CreateUser).HasDefaultValueSql("(user_name())");

            entity.Property(e => e.HasCommercialBillingAlert).HasDefaultValueSql("((0))");

            entity.Property(e => e.HasDowntownCrewPickup).HasDefaultValueSql("((0))");

            entity.Property(e => e.UpdateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.UpdateUser).HasDefaultValueSql("(user_name())");

            entity.HasOne(d => d.Address)
                .WithMany(p => p.CommercialAccount)
                .HasForeignKey(d => d.AddressID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommercialAccount_AddressID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CommercialAccount> entity);
    }
}
