// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models;

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Configurations
{
    public partial class KGISAddressConfiguration : IEntityTypeConfiguration<KGISAddress>
    {
        public void Configure(EntityTypeBuilder<KGISAddress> entity)
        {
            entity.HasNoKey();

            entity.ToTable("KGISAddress");

            entity.Property(e => e.ADDRESS_NUM)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("ADDRESS_NUM");

            entity.Property(e => e.ADDRESS_STATUS)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("ADDRESS_STATUS");

            entity.Property(e => e.ADDRESS_USE_TYPE)
                .HasMaxLength(30)
                .HasColumnName("ADDRESS_USE_TYPE");

            entity.Property(e => e.DATE_OFFICIAL_CHANGE)
                .HasColumnType("date")
                .HasColumnName("DATE_OFFICIAL_CHANGE");

            entity.Property(e => e.JURISDICTION)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("JURISDICTION");

            entity.Property(e => e.LATITUDE)
                .HasColumnType("numeric(38, 8)")
                .HasColumnName("LATITUDE");

            entity.Property(e => e.LONGITUDE)
                .HasColumnType("numeric(38, 8)")
                .HasColumnName("LONGITUDE");

            entity.Property(e => e.OBJECTID)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("OBJECTID");

            entity.Property(e => e.PARCELID)
                .HasMaxLength(50)
                .HasColumnName("PARCELID");

            entity.Property(e => e.POINT_X)
                .HasColumnType("numeric(38, 8)")
                .HasColumnName("POINT_X");

            entity.Property(e => e.POINT_Y)
                .HasColumnType("numeric(38, 8)")
                .HasColumnName("POINT_Y");

            entity.Property(e => e.PREFIX)
                .HasMaxLength(2)
                .HasColumnName("PREFIX");

            entity.Property(e => e.STATE_CODE)
                .HasMaxLength(2)
                .HasColumnName("STATE_CODE");

            entity.Property(e => e.STREET_BASENAME)
                .HasMaxLength(32)
                .HasColumnName("STREET_BASENAME");

            entity.Property(e => e.STREET_NAME)
                .HasMaxLength(50)
                .HasColumnName("STREET_NAME");

            entity.Property(e => e.STREET_TYPE)
                .HasMaxLength(4)
                .HasColumnName("STREET_TYPE");

            entity.Property(e => e.UNIT)
                .HasMaxLength(10)
                .HasColumnName("UNIT");

            entity.Property(e => e.UNIT_TYPE)
                .HasMaxLength(30)
                .HasColumnName("UNIT_TYPE");

            entity.Property(e => e.ZIP_CODE)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("ZIP_CODE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KGISAddress> entity);
    }
}
