// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Models;
using WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle;

namespace WRM_TrashRecyclePopulation.WRM_EntityFramework.WRM_TrashRecycle.Configurations
{
    public partial class KgisaddressConfiguration : IEntityTypeConfiguration<Kgisaddress>
    {
        public void Configure(EntityTypeBuilder<Kgisaddress> entity)
        {
            entity.HasNoKey();

            entity.ToTable("KGISAddress");

            entity.Property(e => e.AddressNum)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("ADDRESS_NUM");

            entity.Property(e => e.AddressStatus)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("ADDRESS_STATUS");

            entity.Property(e => e.AddressUseType)
                .HasMaxLength(30)
                .HasColumnName("ADDRESS_USE_TYPE");

            entity.Property(e => e.DateOfficialChange)
                .HasColumnType("date")
                .HasColumnName("DATE_OFFICIAL_CHANGE");

            entity.Property(e => e.Jurisdiction)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("JURISDICTION");

            entity.Property(e => e.Latitude)
                .HasColumnType("numeric(38, 8)")
                .HasColumnName("LATITUDE");

            entity.Property(e => e.Longitude)
                .HasColumnType("numeric(38, 8)")
                .HasColumnName("LONGITUDE");

            entity.Property(e => e.Objectid)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("OBJECTID");

            entity.Property(e => e.Parcelid)
                .HasMaxLength(50)
                .HasColumnName("PARCELID");

            entity.Property(e => e.PointX)
                .HasColumnType("numeric(38, 8)")
                .HasColumnName("POINT_X");

            entity.Property(e => e.PointY)
                .HasColumnType("numeric(38, 8)")
                .HasColumnName("POINT_Y");

            entity.Property(e => e.Prefix)
                .HasMaxLength(2)
                .HasColumnName("PREFIX");

            entity.Property(e => e.StateCode)
                .HasMaxLength(2)
                .HasColumnName("STATE_CODE");

            entity.Property(e => e.StreetBasename)
                .HasMaxLength(32)
                .HasColumnName("STREET_BASENAME");

            entity.Property(e => e.StreetName)
                .HasMaxLength(50)
                .HasColumnName("STREET_NAME");

            entity.Property(e => e.StreetType)
                .HasMaxLength(4)
                .HasColumnName("STREET_TYPE");

            entity.Property(e => e.Unit)
                .HasMaxLength(10)
                .HasColumnName("UNIT");

            entity.Property(e => e.UnitType)
                .HasMaxLength(30)
                .HasColumnName("UNIT_TYPE");

            entity.Property(e => e.ZipCode)
                .HasColumnType("numeric(38, 0)")
                .HasColumnName("ZIP_CODE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Kgisaddress> entity);
    }
}
